### ISSUE TITLE
Yarn errors on Travis

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-vue#7]
The build is currently failing due to a yarn error:

https://travis-ci.org/honeybadger-io/honeybadger-vue/builds/464185357

**Comment by JasonTrue** [comment]
This turns out to be due to a transitive dependency, har-validator, being unpublished. I'm not sure why it was revoked, but resolving to 5.1.3 seems to do the trick.

I've updated a few transitive dependencies (a bit coarsely; there's probably a case I should force the resolution only in the scope of the parent packages) by using a resolver section in package.json.
